apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-prod-config
  namespace: default
data:
  NEW_FEATURE: "true"

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: spinnaker-prod
  namespace: default
  labels:
    source: prod
    stack: frontend
    app: spinnaker
spec:
  replicas: 3
  selector:
    matchLabels:
      source: prod
      app: spinnaker
  template:
    metadata:
      labels:
        source: prod
        app: spinnaker
    spec:
      containers:
      - name: primary
        image: index.docker.io/cryptocoinmahi/spin
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        envFrom:
        - configMapRef:
            name: spinnaker-prod-config

---

kind: Service
apiVersion: v1
metadata:
  name: spinnaker-prod
  namespace: default
spec:
  selector:
    source: prod
    app: spinnaker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
